// Compiled shader for PC, Mac & Linux Standalone

//////////////////////////////////////////////////////////////////////////
// 
// NOTE: This is *not* a valid shader file, the contents are provided just
// for information and for debugging purposes only.
// 
//////////////////////////////////////////////////////////////////////////
// Skipping shader variants that would not be included into build of current scene.

Shader "Shader Graphs/UnlitSplineShader" {
Properties {
[HideInInspector] [NoScaleOffset]  unity_Lightmaps ("unity_Lightmaps", 2DArray) = "" { }
[HideInInspector] [NoScaleOffset]  unity_LightmapsInd ("unity_LightmapsInd", 2DArray) = "" { }
[HideInInspector] [NoScaleOffset]  unity_ShadowMasks ("unity_ShadowMasks", 2DArray) = "" { }
}
SubShader { 
 Tags { "QUEUE"="Geometry" "RenderType"="Opaque" "RenderPipeline"="UniversalPipeline" "UniversalMaterialType"="Unlit" }


 // Stats for Vertex shader:
 //        d3d11: 8 math
 // Stats for Fragment shader:
 //        d3d11: 15 math
 Pass {
  Name "Pass"
  Tags { "QUEUE"="Geometry" "RenderType"="Opaque" "RenderPipeline"="UniversalPipeline" "UniversalMaterialType"="Unlit" }
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Global Keywords: <none>
Local Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 8 math, 2 temp registers
Uses vertex data channel "Vertex"

Constant Buffer "$Globals" (1952 bytes) on slot 0 {
  Matrix4x4 unity_MatrixVP at 1120
}
Constant Buffer "UnityPerDraw" (400 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float       
// TANGENT                  0   xyzw        2     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
//
      vs_4_0
      dcl_constantbuffer CB0[74], immediateIndexed
      dcl_constantbuffer CB1[4], immediateIndexed
      dcl_input v0.xyz
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyz
      dcl_temps 2
   0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
   1: mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
   2: mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
   3: add r0.xyz, r0.xyzx, cb1[3].xyzx
   4: mul r1.xyzw, r0.yyyy, cb0[71].xyzw
   5: mad r1.xyzw, cb0[70].xyzw, r0.xxxx, r1.xyzw
   6: mad r1.xyzw, cb0[72].xyzw, r0.zzzz, r1.xyzw
   7: mov o1.xyz, r0.xyzx
   8: add o0.xyzw, r1.xyzw, cb0[73].xyzw
   9: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 15 math, 3 temp registers
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyz         1     NONE   float    y  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_input_ps linear v1.y
      dcl_output o0.xyzw
      dcl_temps 3
   0: add r0.xyzw, v1.yyyy, l(0.500000, 0.226467, 0.029412, -0.211772)
   1: mul_sat r0.xyzw, r0.xyzw, l(3.655864, 5.074725, 4.146210, 7.234243)
   2: mad r1.xyz, r0.xxxx, l(0.992607, -0.483246, 0.000000, 0.000000), l(0.007393, 1.000000, 0.000000, 0.000000)
   3: add r2.xyz, -r1.xyzx, l(1.000000, 0.000000, 0.995011, 0.000000)
   4: mad r1.xyz, r0.yyyy, r2.xyzx, r1.xyzx
   5: add r2.xyz, -r1.xyzx, l(1.000000, 0.000000, 0.554040, 0.000000)
   6: mad r0.xyz, r0.zzzz, r2.xyzx, r1.xyzx
   7: add r1.xyz, -r0.xyzx, l(1.000000, 0.000000, 0.000000, 0.000000)
   8: mad r0.xyz, r0.wwww, r1.xyzx, r0.xyzx
   9: log r1.xyz, |r0.xyzx|
  10: mul r1.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
  11: exp r1.xyz, r1.xyzx
  12: mad r1.xyz, r1.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
  13: mul r2.xyz, r0.xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
  14: ge r0.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), r0.xyzx
  15: movc o0.xyz, r0.xyzx, r2.xyzx, r1.xyzx
  16: mov o0.w, l(1.000000)
  17: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Global Keywords: DIRLIGHTMAP_COMBINED 
Local Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 8 math, 2 temp registers
Uses vertex data channel "Vertex"

Constant Buffer "$Globals" (1952 bytes) on slot 0 {
  Matrix4x4 unity_MatrixVP at 1120
}
Constant Buffer "UnityPerDraw" (400 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float       
// TANGENT                  0   xyzw        2     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
//
      vs_4_0
      dcl_constantbuffer CB0[74], immediateIndexed
      dcl_constantbuffer CB1[4], immediateIndexed
      dcl_input v0.xyz
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyz
      dcl_temps 2
   0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
   1: mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
   2: mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
   3: add r0.xyz, r0.xyzx, cb1[3].xyzx
   4: mul r1.xyzw, r0.yyyy, cb0[71].xyzw
   5: mad r1.xyzw, cb0[70].xyzw, r0.xxxx, r1.xyzw
   6: mad r1.xyzw, cb0[72].xyzw, r0.zzzz, r1.xyzw
   7: mov o1.xyz, r0.xyzx
   8: add o0.xyzw, r1.xyzw, cb0[73].xyzw
   9: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 15 math, 3 temp registers
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyz         1     NONE   float    y  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_input_ps linear v1.y
      dcl_output o0.xyzw
      dcl_temps 3
   0: add r0.xyzw, v1.yyyy, l(0.500000, 0.226467, 0.029412, -0.211772)
   1: mul_sat r0.xyzw, r0.xyzw, l(3.655864, 5.074725, 4.146210, 7.234243)
   2: mad r1.xyz, r0.xxxx, l(0.992607, -0.483246, 0.000000, 0.000000), l(0.007393, 1.000000, 0.000000, 0.000000)
   3: add r2.xyz, -r1.xyzx, l(1.000000, 0.000000, 0.995011, 0.000000)
   4: mad r1.xyz, r0.yyyy, r2.xyzx, r1.xyzx
   5: add r2.xyz, -r1.xyzx, l(1.000000, 0.000000, 0.554040, 0.000000)
   6: mad r0.xyz, r0.zzzz, r2.xyzx, r1.xyzx
   7: add r1.xyz, -r0.xyzx, l(1.000000, 0.000000, 0.000000, 0.000000)
   8: mad r0.xyz, r0.wwww, r1.xyzx, r0.xyzx
   9: log r1.xyz, |r0.xyzx|
  10: mul r1.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
  11: exp r1.xyz, r1.xyzx
  12: mad r1.xyz, r1.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
  13: mul r2.xyz, r0.xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
  14: ge r0.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), r0.xyzx
  15: movc o0.xyz, r0.xyzx, r2.xyzx, r1.xyzx
  16: mov o0.w, l(1.000000)
  17: ret 
// Approximately 0 instruction slots used


 }


 // Stats for Vertex shader:
 //        d3d11: 23 avg math (21..25)
 Pass {
  Name "ShadowCaster"
  Tags { "LIGHTMODE"="SHADOWCASTER" "QUEUE"="Geometry" "RenderType"="Opaque" "RenderPipeline"="UniversalPipeline" "UniversalMaterialType"="Unlit" }
  ColorMask 0
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Global Keywords: <none>
Local Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 21 math, 2 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Normal"

Constant Buffer "$Globals" (1984 bytes) on slot 0 {
  Matrix4x4 unity_MatrixVP at 1120
  Vector4 _ShadowBias at 1936
  Vector3 _LightDirection at 1952
}
Constant Buffer "UnityPerDraw" (400 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[123], immediateIndexed
      dcl_constantbuffer CB1[7], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyz
      dcl_output_siv o0.xyzw, position
      dcl_temps 2
   0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
   1: mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
   2: mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
   3: add r0.xyz, r0.xyzx, cb1[3].xyzx
   4: mad r0.xyz, cb0[122].xyzx, cb0[121].xxxx, r0.xyzx
   5: dp3 r1.x, v1.xyzx, cb1[4].xyzx
   6: dp3 r1.y, v1.xyzx, cb1[5].xyzx
   7: dp3 r1.z, v1.xyzx, cb1[6].xyzx
   8: dp3 r0.w, r1.xyzx, r1.xyzx
   9: max r0.w, r0.w, l(0.000000)
  10: rsq r0.w, r0.w
  11: mul r1.xyz, r0.wwww, r1.xyzx
  12: dp3_sat r0.w, cb0[122].xyzx, r1.xyzx
  13: add r0.w, -r0.w, l(1.000000)
  14: mul r0.w, r0.w, cb0[121].y
  15: mad r0.xyz, r1.xyzx, r0.wwww, r0.xyzx
  16: mul r1.xyzw, r0.yyyy, cb0[71].xyzw
  17: mad r1.xyzw, cb0[70].xyzw, r0.xxxx, r1.xyzw
  18: mad r0.xyzw, cb0[72].xyzw, r0.zzzz, r1.xyzw
  19: add r0.xyzw, r0.xyzw, cb0[73].xyzw
  20: min o0.z, r0.z, l(1.000000)
  21: mov o0.xyw, r0.xyxw
  22: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0,0,0,0)
   1: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Global Keywords: _CASTING_PUNCTUAL_LIGHT_SHADOW 
Local Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 25 math, 3 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Normal"

Constant Buffer "$Globals" (1984 bytes) on slot 0 {
  Matrix4x4 unity_MatrixVP at 1120
  Vector4 _ShadowBias at 1936
  Vector3 _LightPosition at 1968
}
Constant Buffer "UnityPerDraw" (400 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[124], immediateIndexed
      dcl_constantbuffer CB1[7], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyz
      dcl_output_siv o0.xyzw, position
      dcl_temps 3
   0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
   1: mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
   2: mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
   3: add r0.xyz, r0.xyzx, cb1[3].xyzx
   4: add r1.xyz, -r0.xyzx, cb0[123].xyzx
   5: dp3 r0.w, r1.xyzx, r1.xyzx
   6: rsq r0.w, r0.w
   7: mul r1.xyz, r0.wwww, r1.xyzx
   8: mad r0.xyz, r1.xyzx, cb0[121].xxxx, r0.xyzx
   9: dp3 r2.x, v1.xyzx, cb1[4].xyzx
  10: dp3 r2.y, v1.xyzx, cb1[5].xyzx
  11: dp3 r2.z, v1.xyzx, cb1[6].xyzx
  12: dp3 r0.w, r2.xyzx, r2.xyzx
  13: max r0.w, r0.w, l(0.000000)
  14: rsq r0.w, r0.w
  15: mul r2.xyz, r0.wwww, r2.xyzx
  16: dp3_sat r0.w, r1.xyzx, r2.xyzx
  17: add r0.w, -r0.w, l(1.000000)
  18: mul r0.w, r0.w, cb0[121].y
  19: mad r0.xyz, r2.xyzx, r0.wwww, r0.xyzx
  20: mul r1.xyzw, r0.yyyy, cb0[71].xyzw
  21: mad r1.xyzw, cb0[70].xyzw, r0.xxxx, r1.xyzw
  22: mad r0.xyzw, cb0[72].xyzw, r0.zzzz, r1.xyzw
  23: add r0.xyzw, r0.xyzw, cb0[73].xyzw
  24: min o0.z, r0.z, l(1.000000)
  25: mov o0.xyw, r0.xyxw
  26: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0,0,0,0)
   1: ret 
// Approximately 0 instruction slots used


 }


 // Stats for Vertex shader:
 //        d3d11: 8 math
 Pass {
  Name "DepthOnly"
  Tags { "LIGHTMODE"="DepthOnly" "QUEUE"="Geometry" "RenderType"="Opaque" "RenderPipeline"="UniversalPipeline" "UniversalMaterialType"="Unlit" }
  ColorMask 0
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Global Keywords: <none>
Local Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 8 math, 2 temp registers
Uses vertex data channel "Vertex"

Constant Buffer "$Globals" (1952 bytes) on slot 0 {
  Matrix4x4 unity_MatrixVP at 1120
}
Constant Buffer "UnityPerDraw" (400 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float       
// TANGENT                  0   xyzw        2     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[74], immediateIndexed
      dcl_constantbuffer CB1[4], immediateIndexed
      dcl_input v0.xyz
      dcl_output_siv o0.xyzw, position
      dcl_temps 2
   0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
   1: mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
   2: mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
   3: add r0.xyz, r0.xyzx, cb1[3].xyzx
   4: mul r1.xyzw, r0.yyyy, cb0[71].xyzw
   5: mad r1.xyzw, cb0[70].xyzw, r0.xxxx, r1.xyzw
   6: mad r0.xyzw, cb0[72].xyzw, r0.zzzz, r1.xyzw
   7: add o0.xyzw, r0.xyzw, cb0[73].xyzw
   8: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0,0,0,0)
   1: ret 
// Approximately 0 instruction slots used


 }
}
SubShader { 
 Tags { "QUEUE"="Geometry" "RenderType"="Opaque" "RenderPipeline"="UniversalPipeline" "UniversalMaterialType"="Unlit" }


 // Stats for Vertex shader:
 //        d3d11: 8 math
 // Stats for Fragment shader:
 //        d3d11: 15 math
 Pass {
  Name "Pass"
  Tags { "QUEUE"="Geometry" "RenderType"="Opaque" "RenderPipeline"="UniversalPipeline" "UniversalMaterialType"="Unlit" }
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Global Keywords: <none>
Local Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 8 math, 2 temp registers
Uses vertex data channel "Vertex"

Constant Buffer "$Globals" (1952 bytes) on slot 0 {
  Matrix4x4 unity_MatrixVP at 1120
}
Constant Buffer "UnityPerDraw" (400 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float       
// TANGENT                  0   xyzw        2     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
//
      vs_5_0
      dcl_globalFlags refactoringAllowed
      dcl_constantbuffer CB0[74], immediateIndexed
      dcl_constantbuffer CB1[4], immediateIndexed
      dcl_input v0.xyz
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyz
      dcl_temps 2
   0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
   1: mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
   2: mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
   3: add r0.xyz, r0.xyzx, cb1[3].xyzx
   4: mul r1.xyzw, r0.yyyy, cb0[71].xyzw
   5: mad r1.xyzw, cb0[70].xyzw, r0.xxxx, r1.xyzw
   6: mad r1.xyzw, cb0[72].xyzw, r0.zzzz, r1.xyzw
   7: mov o1.xyz, r0.xyzx
   8: add o0.xyzw, r1.xyzw, cb0[73].xyzw
   9: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 15 math, 3 temp registers
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyz         1     NONE   float    y  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_5_0
      dcl_globalFlags refactoringAllowed
      dcl_input_ps linear v1.y
      dcl_output o0.xyzw
      dcl_temps 3
   0: add r0.xyzw, v1.yyyy, l(0.500000, 0.226467, 0.029412, -0.211772)
   1: mul_sat r0.xyzw, r0.xyzw, l(3.655864, 5.074725, 4.146210, 7.234243)
   2: mad r1.xyz, r0.xxxx, l(0.992607, -0.483246, 0.000000, 0.000000), l(0.007393, 1.000000, 0.000000, 0.000000)
   3: add r2.xyz, -r1.xyzx, l(1.000000, 0.000000, 0.995011, 0.000000)
   4: mad r1.xyz, r0.yyyy, r2.xyzx, r1.xyzx
   5: add r2.xyz, -r1.xyzx, l(1.000000, 0.000000, 0.554040, 0.000000)
   6: mad r0.xyz, r0.zzzz, r2.xyzx, r1.xyzx
   7: add r1.xyz, -r0.xyzx, l(1.000000, 0.000000, 0.000000, 0.000000)
   8: mad r0.xyz, r0.wwww, r1.xyzx, r0.xyzx
   9: log r1.xyz, |r0.xyzx|
  10: mul r1.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
  11: exp r1.xyz, r1.xyzx
  12: mad r1.xyz, r1.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
  13: mul r2.xyz, r0.xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
  14: ge r0.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), r0.xyzx
  15: movc o0.xyz, r0.xyzx, r2.xyzx, r1.xyzx
  16: mov o0.w, l(1.000000)
  17: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Global Keywords: DIRLIGHTMAP_COMBINED 
Local Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 8 math, 2 temp registers
Uses vertex data channel "Vertex"

Constant Buffer "$Globals" (1952 bytes) on slot 0 {
  Matrix4x4 unity_MatrixVP at 1120
}
Constant Buffer "UnityPerDraw" (400 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float       
// TANGENT                  0   xyzw        2     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
//
      vs_5_0
      dcl_globalFlags refactoringAllowed
      dcl_constantbuffer CB0[74], immediateIndexed
      dcl_constantbuffer CB1[4], immediateIndexed
      dcl_input v0.xyz
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyz
      dcl_temps 2
   0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
   1: mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
   2: mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
   3: add r0.xyz, r0.xyzx, cb1[3].xyzx
   4: mul r1.xyzw, r0.yyyy, cb0[71].xyzw
   5: mad r1.xyzw, cb0[70].xyzw, r0.xxxx, r1.xyzw
   6: mad r1.xyzw, cb0[72].xyzw, r0.zzzz, r1.xyzw
   7: mov o1.xyz, r0.xyzx
   8: add o0.xyzw, r1.xyzw, cb0[73].xyzw
   9: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 15 math, 3 temp registers
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyz         1     NONE   float    y  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_5_0
      dcl_globalFlags refactoringAllowed
      dcl_input_ps linear v1.y
      dcl_output o0.xyzw
      dcl_temps 3
   0: add r0.xyzw, v1.yyyy, l(0.500000, 0.226467, 0.029412, -0.211772)
   1: mul_sat r0.xyzw, r0.xyzw, l(3.655864, 5.074725, 4.146210, 7.234243)
   2: mad r1.xyz, r0.xxxx, l(0.992607, -0.483246, 0.000000, 0.000000), l(0.007393, 1.000000, 0.000000, 0.000000)
   3: add r2.xyz, -r1.xyzx, l(1.000000, 0.000000, 0.995011, 0.000000)
   4: mad r1.xyz, r0.yyyy, r2.xyzx, r1.xyzx
   5: add r2.xyz, -r1.xyzx, l(1.000000, 0.000000, 0.554040, 0.000000)
   6: mad r0.xyz, r0.zzzz, r2.xyzx, r1.xyzx
   7: add r1.xyz, -r0.xyzx, l(1.000000, 0.000000, 0.000000, 0.000000)
   8: mad r0.xyz, r0.wwww, r1.xyzx, r0.xyzx
   9: log r1.xyz, |r0.xyzx|
  10: mul r1.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
  11: exp r1.xyz, r1.xyzx
  12: mad r1.xyz, r1.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
  13: mul r2.xyz, r0.xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
  14: ge r0.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), r0.xyzx
  15: movc o0.xyz, r0.xyzx, r2.xyzx, r1.xyzx
  16: mov o0.w, l(1.000000)
  17: ret 
// Approximately 0 instruction slots used


 }


 // Stats for Vertex shader:
 //        d3d11: 23 avg math (21..25)
 Pass {
  Name "ShadowCaster"
  Tags { "LIGHTMODE"="SHADOWCASTER" "QUEUE"="Geometry" "RenderType"="Opaque" "RenderPipeline"="UniversalPipeline" "UniversalMaterialType"="Unlit" }
  ColorMask 0
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Global Keywords: <none>
Local Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 21 math, 2 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Normal"

Constant Buffer "$Globals" (1984 bytes) on slot 0 {
  Matrix4x4 unity_MatrixVP at 1120
  Vector4 _ShadowBias at 1936
  Vector3 _LightDirection at 1952
}
Constant Buffer "UnityPerDraw" (400 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_5_0
      dcl_globalFlags refactoringAllowed
      dcl_constantbuffer CB0[123], immediateIndexed
      dcl_constantbuffer CB1[7], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyz
      dcl_output_siv o0.xyzw, position
      dcl_temps 2
   0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
   1: mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
   2: mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
   3: add r0.xyz, r0.xyzx, cb1[3].xyzx
   4: mad r0.xyz, cb0[122].xyzx, cb0[121].xxxx, r0.xyzx
   5: dp3 r1.x, v1.xyzx, cb1[4].xyzx
   6: dp3 r1.y, v1.xyzx, cb1[5].xyzx
   7: dp3 r1.z, v1.xyzx, cb1[6].xyzx
   8: dp3 r0.w, r1.xyzx, r1.xyzx
   9: max r0.w, r0.w, l(0.000000)
  10: rsq r0.w, r0.w
  11: mul r1.xyz, r0.wwww, r1.xyzx
  12: dp3_sat r0.w, cb0[122].xyzx, r1.xyzx
  13: add r0.w, -r0.w, l(1.000000)
  14: mul r0.w, r0.w, cb0[121].y
  15: mad r0.xyz, r1.xyzx, r0.wwww, r0.xyzx
  16: mul r1.xyzw, r0.yyyy, cb0[71].xyzw
  17: mad r1.xyzw, cb0[70].xyzw, r0.xxxx, r1.xyzw
  18: mad r0.xyzw, cb0[72].xyzw, r0.zzzz, r1.xyzw
  19: add r0.xyzw, r0.xyzw, cb0[73].xyzw
  20: min o0.z, r0.z, l(1.000000)
  21: mov o0.xyw, r0.xyxw
  22: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_5_0
      dcl_globalFlags refactoringAllowed
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0,0,0,0)
   1: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Global Keywords: _CASTING_PUNCTUAL_LIGHT_SHADOW 
Local Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 25 math, 3 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Normal"

Constant Buffer "$Globals" (1984 bytes) on slot 0 {
  Matrix4x4 unity_MatrixVP at 1120
  Vector4 _ShadowBias at 1936
  Vector3 _LightPosition at 1968
}
Constant Buffer "UnityPerDraw" (400 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_5_0
      dcl_globalFlags refactoringAllowed
      dcl_constantbuffer CB0[124], immediateIndexed
      dcl_constantbuffer CB1[7], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyz
      dcl_output_siv o0.xyzw, position
      dcl_temps 3
   0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
   1: mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
   2: mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
   3: add r0.xyz, r0.xyzx, cb1[3].xyzx
   4: add r1.xyz, -r0.xyzx, cb0[123].xyzx
   5: dp3 r0.w, r1.xyzx, r1.xyzx
   6: rsq r0.w, r0.w
   7: mul r1.xyz, r0.wwww, r1.xyzx
   8: mad r0.xyz, r1.xyzx, cb0[121].xxxx, r0.xyzx
   9: dp3 r2.x, v1.xyzx, cb1[4].xyzx
  10: dp3 r2.y, v1.xyzx, cb1[5].xyzx
  11: dp3 r2.z, v1.xyzx, cb1[6].xyzx
  12: dp3 r0.w, r2.xyzx, r2.xyzx
  13: max r0.w, r0.w, l(0.000000)
  14: rsq r0.w, r0.w
  15: mul r2.xyz, r0.wwww, r2.xyzx
  16: dp3_sat r0.w, r1.xyzx, r2.xyzx
  17: add r0.w, -r0.w, l(1.000000)
  18: mul r0.w, r0.w, cb0[121].y
  19: mad r0.xyz, r2.xyzx, r0.wwww, r0.xyzx
  20: mul r1.xyzw, r0.yyyy, cb0[71].xyzw
  21: mad r1.xyzw, cb0[70].xyzw, r0.xxxx, r1.xyzw
  22: mad r0.xyzw, cb0[72].xyzw, r0.zzzz, r1.xyzw
  23: add r0.xyzw, r0.xyzw, cb0[73].xyzw
  24: min o0.z, r0.z, l(1.000000)
  25: mov o0.xyw, r0.xyxw
  26: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_5_0
      dcl_globalFlags refactoringAllowed
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0,0,0,0)
   1: ret 
// Approximately 0 instruction slots used


 }


 // Stats for Vertex shader:
 //        d3d11: 8 math
 Pass {
  Name "DepthOnly"
  Tags { "LIGHTMODE"="DepthOnly" "QUEUE"="Geometry" "RenderType"="Opaque" "RenderPipeline"="UniversalPipeline" "UniversalMaterialType"="Unlit" }
  ColorMask 0
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Global Keywords: <none>
Local Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 8 math, 2 temp registers
Uses vertex data channel "Vertex"

Constant Buffer "$Globals" (1952 bytes) on slot 0 {
  Matrix4x4 unity_MatrixVP at 1120
}
Constant Buffer "UnityPerDraw" (400 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float       
// TANGENT                  0   xyzw        2     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_5_0
      dcl_globalFlags refactoringAllowed
      dcl_constantbuffer CB0[74], immediateIndexed
      dcl_constantbuffer CB1[4], immediateIndexed
      dcl_input v0.xyz
      dcl_output_siv o0.xyzw, position
      dcl_temps 2
   0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
   1: mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
   2: mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
   3: add r0.xyz, r0.xyzx, cb1[3].xyzx
   4: mul r1.xyzw, r0.yyyy, cb0[71].xyzw
   5: mad r1.xyzw, cb0[70].xyzw, r0.xxxx, r1.xyzw
   6: mad r0.xyzw, cb0[72].xyzw, r0.zzzz, r1.xyzw
   7: add o0.xyzw, r0.xyzw, cb0[73].xyzw
   8: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_5_0
      dcl_globalFlags refactoringAllowed
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0,0,0,0)
   1: ret 
// Approximately 0 instruction slots used


 }
}
Fallback "Hidden/Shader Graph/FallbackError"
}